"""added_models_into_db

Revision ID: 2e5fe61fddb6
Revises: 
Create Date: 2025-08-06 22:47:27.683983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5fe61fddb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('course_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_status_id'), 'course_status', ['id'], unique=False)
    op.create_table('finished_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cert_id', sa.Integer(), nullable=True),
    sa.Column('link_cert', sa.Text(), nullable=False),
    sa.Column('course_hauor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_cert_id'], ['course_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_courses_id'), 'finished_courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_courses_id'), table_name='finished_courses')
    op.drop_table('finished_courses')
    op.drop_index(op.f('ix_course_status_id'), table_name='course_status')
    op.drop_table('course_status')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
